### ISSUE TITLE
Updating from macOS 11.6.4 to 12.3.1 

### ISSUE THREAD

**Issue by commet24** [RobyRew/ASUS-FX504GE-Hackintosh_OpenCore#14]
I have 0.7.9 version GoodAudio-NoHDMI config.

When i trying to update my Hackintosh from Big Sur to Monterey I have an error:
![I have an error](https://user-images.githubusercontent.com/98208599/163240019-0371cb73-6fe2-4c0e-b7c0-2f14d9b32476.jpg)

**Comment by RobyRew** [comment]
First of all, your laptop is same model as mine, right?
change **Misc > Security > BlacklistAppleUpdate > False** 
![image](https://user-images.githubusercontent.com/49403384/163279595-406b348d-45ea-4933-b9d9-90f91f073a6e.png)
Config already edited:, (you need to add your own SMBIOS, SN, UUID, etc..)
[config.zip](https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_OpenCore/files/8485020/config.zip)

I had it like that because I normally do not update until past few month of big new OS release, so I have updates blacklisted, don't know if is because that reason, can you confirm ?

**Comment by commet24** [comment]
> First of all, your laptop is same model as mine, right?

No, my laptop is FX504GD with Core i5-8300H, but it does not matter I think.

**Comment by RobyRew** [comment]
> UPD: Now I reset my NVRAM and tried to update again. Hope that helps. Used your attached config with changed platform-info (SMBIOS, etc.)
> 
> 
> 
> Yes!! It worked. Thank you!

there maybe some differences like FX504GM has a totally different dGPU iGPU layout co configuration, but everything else is identical.
The FX504GD I think is pretty similar if not identical as FX504GE.

Anyway...

Awesome to hear that, I'll be committing that on future release so it ends the problem.

Thanks a lot for your helping enjoy you hackintosh!!! ❤️
