### ISSUE TITLE
HDMI port doesn't have any outputs

### ISSUE THREAD

**Issue by xinjiempolde** [RobyRew/ASUS-FX504GE-Hackintosh_OpenCore#16]
Thanks for your EFI files. I have installed BigSur 11.3.1 on FX504GE and everything works well except the HDMI port. It doesn't have any output. Could you please give me some advice?

**Comment by RobyRew** [comment]
> Thanks for your EFI files. I have installed BigSur 11.3.1 on FX504GE and everything works well except the HDMI port. It doesn't have any output. Could you please give me some advice?

did you use the provided EFI from the latest RELEASE?? https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_OpenCore/releases
What cable and monitor you're using to try the HDMI?

**Comment by xinjiempolde** [comment]
> > Thanks for your EFI files. I have installed BigSur 11.3.1 on FX504GE and everything works well except the HDMI port. It doesn't have any output. Could you please give me some advice?
> 
> did you use the provided EFI from the latest RELEASE?? https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_OpenCore/releases What cable and monitor you're using to try the HDMI?

I used the EFI from the RELEASE0.8.3(https://github.com/RobyRew/ASUS-FX504GE-Hackintosh_OpenCore/releases/tag/0.8.3) which is the latest release when I install macOS. I used HDMI cable to connect 1080p monitor and nothing happened. So I used EFI from https://github.com/wilsomwong/Asus-TUF-FX504GE-Hackintosh   . I didn't known what configuration has been changed but everything did work well including HDMI output. Anyway, thanks for your work and your reply!

**Comment by RobyRew** [comment]
> I didn't known what configuration has been changed but everything did work well including HDMI output. Anyway, thanks for your work and your reply!

I just rebuilt the entire EFI making sure everything is how I know its well configured.

BTW, if you installed BigSur and don't want to use the latest macOS Ventura, to be able to have Bluetooth and Wifi you need to change some things on the EFI, because those drivers are not compatible within different OS Updates.

My recommendation is you to use Ventura, but hey if you really don't want it I can help you with setting up Wifi and Bluetooth.

Have a good day! 😉
